[tool.poetry]
name = "hp"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"
SQLAlchemy = "2.0.21"
psycopg2-binary = "2.9.7"
requests = "2.31.0"
selenium = "^4.15.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
